---
# Configure elasticsearch as the database

- name: Copy elasticsearch yum repo file
  copy: src=elasticsearch.repo
        dest=/etc/yum.repos.d/

- name: Install elasticsearch
  yum: name=elasticsearch state=latest

- name: Start elasticsearch
  service: name=elasticsearch enabled=yes state=started