---
# Configure elasticsearch as the database

- name: Add elasticsearch signing key
  command: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Copy elasticsearch yum repo file
  copy: src=files/elasticsearch.repo
        dest=/etc/yum.repos.d/

- name: Install elasticsearch
  yum: name=elasticsearch state=latest

- name: Start elasticsearch
  service: name=elasticsearch enabled=yes state=started