---
# Configure load balancing over the tile servers with nginx

- name: Prepare nginx repo (RedHat)
  copy: src=nginx.repo
        dest=/etc/yum.repos.d/
  when: ansible_os_family == "RedHat"

- name: Prepare nginx repo (Debian)
  shell: add-apt-repository ppa:nginx/$nginx
  when: ansible_os_family == "Debian"

- name: Install nginx (RedHat)
  yum: name=nginx state=present
  when: ansible_os_family == "RedHat"

- name: Install nginx (Debian)
  apt: name=nginx state=present
  when: ansible_os_family == "Debian"

- name: Copy nginx configuration
  template: src=nginx.j2 
            dest=/etc/nginx/conf.d/default.conf
  notify: Restart load_balancing

- name: Start nginx
  service: name=nginx enabled=yes state=started