---
# Configure the tile servers

- name: Add node.js repo (RedHat)
  shell: curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
  when: ansible_os_family == "RedHat"

- name: Add node.js repo (Debian)
  shell: curl -sL https://deb.nodesource.com/setup_6.x | bash -
  when: ansible_os_family == "Debian"

- name: Install node (RedHat)
  yum: name=nodejs state=present
  when: ansible_os_family == "RedHat"

- name: Install node (Debian)
  apt: name=nodejs state=present
  when: ansible_os_family == "Debian"

- name: Install tile server
  npm: name=tileserver-gl-light global=yes state=latest

- name: Copy vector tile file
  copy: src={{ vector_file }}.mbtiles
        dest=/etc/yum.repos.d/