---
# Configure the tile servers

- name: Add node.js repo (RedHat)
  shell: curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
  when: ansible_os_family == "RedHat"

- name: Add node.js repo (Debian)
  shell: curl -sL https://deb.nodesource.com/setup_6.x | bash -
  when: ansible_os_family == "Debian"

- name: Install node (RedHat)
  yum: name=nodejs state=present
  when: ansible_os_family == "RedHat"

- name: Install node (Debian)
  apt: name=nodejs state=present
  when: ansible_os_family == "Debian"

- name: Install tile server
  npm: name=tileserver-gl-light global=yes state=latest version=1.3.2

- name: Copy vector tile files
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: '{{ vector_file }}.mbtiles', dest: '/hosting/data/' }
    - { src: 'style.json', dest: '/hosting/styles/' }
    - { src: 'sprite.json', dest: '/hosting/styles/kibana.json' }
    - { src: 'sprite.png', dest: '/hosting/styles/kibana.png' }
    - { src: 'config.json', dest: '/hosting/config/' }
    - { src: 'Open Sans Regular', dest: '/hosting/fonts/' }
  notify: Restart tilers (step 1)

- name: Install at (RedHat)
  yum: name=at state=present
  when: ansible_os_family == "RedHat"

- name: Start atd (RedHat)
  service: name=atd enabled=yes state=started
  when: ansible_os_family == "RedHat"

- name: Start tile server
  shell: echo "tileserver-gl-light --config /hosting/config/config.json > /dev/null" | at now