---
# Configure kibana as the site monitoring tool

- name: Add node.js repo (RedHat)
  shell: curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
  when: ansible_os_family == "RedHat"

- name: Add node.js repo (Debian)
  shell: curl -sL https://deb.nodesource.com/setup_6.x | bash -
  when: ansible_os_family == "Debian"

- name: Install node (RedHat)
  yum: name=nodejs state=present
  when: ansible_os_family == "RedHat"

- name: Install node (Debian)
  apt: name=nodejs state=present
  when: ansible_os_family == "Debian"

- name: Install git (RedHat)
  yum: name=git state=latest
  when: ansible_os_family == "RedHat"

- name: Install git (Debian)
  apt: name=git state=latest
  when: ansible_os_family == "Debian"

- name: Install at (RedHat)
  yum: name=at state=present
  when: ansible_os_family == "RedHat"

- name: Start atd (RedHat)
  service: name=atd enabled=yes state=started
  when: ansible_os_family == "RedHat"

- name: Clone git repo
  git: 
    repo: https://github.com/lrakai/kibana.git
    dest: "{{ src_path }}"
    version: 5.2-vector-map

- name: Install kibana packages
  shell: "cd {{ src_path }} && sudo npm install --production || true"

- name: Prepare kibana configuration file
  copy: src=kibana.yml
        dest={{ src_path }}/config
  notify: Restart monitor (step 1)

- name: Start kibana
  shell: echo "sudo bash {{ src_path }}/bin/kibana > /dev/null" | at now